"""Externally-authored corpora, fetched rather than vendored.

This project's own corpus was written here, so its numbers flatter whatever it
was written alongside. That is stated in the README, but stating a bias does
not remove it. The corpora below were authored by other people, and every one
of them has found a real bug that this project's own cases did not.

They are fetched to a gitignored cache and never committed, for the same
reason the generated payloads are never committed: these are working exploits,
not inert markers like the ones in `cases.py`. Nothing here loads or unpickles
them. They are scanned as bytes.

Ground truth is taken from each corpus's own labelling and never guessed. Where
a file's label is not stated by its author, it is excluded from scoring rather
than assigned one, because inventing labels is how a benchmark quietly becomes
a measurement of its own assumptions.
"""

from __future__ import annotations

import io
import shutil
import tarfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path

CACHE_DIR = Path(__file__).resolve().parent.parent / "external-cache"


@dataclass(frozen=True)
class ExternalCorpus:
    """One externally-authored corpus."""

    id: str
    name: str
    # Pinned to a commit, never to a branch head. These corpora are upstream
    # repositories that keep moving, so `refs/heads/main` meant every number
    # published against them was measured on a snapshot nobody could name and
    # nobody could get back. That is the same failure the benign manifest pins
    # SHA-256 to avoid, and it had no business being treated differently just
    # because the source is a git host.
    url: str
    commit: str
    # Archive members under this path are the corpus.
    member_prefix: str
    license: str
    origin: str
    note: str = ""
    # Files whose label the corpus author does not state. Scored as neither.
    unlabelled: frozenset[str] = frozenset()
    # Files the author's tests assert malicious despite a name outside the
    # malicious* convention. Evidence over convention.
    asserted_malicious: frozenset[str] = frozenset()
    # When set, every file in the corpus is malicious by construction.
    all_malicious: bool = False


CORPORA: tuple[ExternalCorpus, ...] = (
    ExternalCorpus(
        id="picklescan-tests",
        name="picklescan test corpus",
        url="https://github.com/mmaitre314/picklescan/archive/f15d54da3dec9aa28a87ede82f87882bb80f1023.tar.gz",
        commit="f15d54da3dec9aa28a87ede82f87882bb80f1023",
        member_prefix="tests/data/",
        license="MIT",
        origin="https://github.com/mmaitre314/picklescan",
        note=(
            "picklescan's own test suite, so picklescan scores near-perfectly "
            "on it by construction and its column here means little. The "
            "informative columns are everyone else's. Labels come from the "
            "filename convention the author uses (malicious* / benign*)."
        ),
        # Names whose label picklescan's own tests do not state unambiguously.
        # `bad_pytorch.pt` is a PNG with a .pt extension and `not_a_pickle.bin`
        # is not a pickle at all, so neither is malicious *or* a clean model.
        unlabelled=frozenset({
            "broken_model.pkl", "bad_pytorch.pt", "not_a_pickle.bin",
            "pytorch_model.bin", "new_pytorch_model.bin",
            "sys_module_override_sploit.pkl",
            "benign_password_protected.zip",
        }),
        # picklescan's tests/test_scanner.py asserts this file yields two
        # dangerous globals (__builtin__.eval in the magic pickle, posix.system
        # in the payload). The author's label wins over the filename
        # convention; a benchmark contradicting the corpus author is the first
        # thing a critic finds.
        asserted_malicious=frozenset({"pytorch_magic_bypass.pt"}),
    ),
    ExternalCorpus(
        id="picklecloak-exploits",
        name="PickleCloak gadget exploits",
        url="https://github.com/Lyutoon/PickleCloak/archive/909fff715f065d690c3d5475f324a931d97349fc.tar.gz",
        commit="909fff715f065d690c3d5475f324a931d97349fc",
        member_prefix="gadget/exploits/malicious_pkls/",
        license="none declared (all rights reserved)",
        origin="https://github.com/Lyutoon/PickleCloak",
        note=(
            "Generated by a static-analysis plus LLM pipeline that mines the "
            "standard library for gadget chains, so it contains resolvers "
            "nobody has put on a list. Payloads are benign commands (touch, "
            "ls, whoami) per the authors' ethics statement. NO BENIGN HALF: a "
            "scanner that flags every file scores 100%, so read detection "
            "here only alongside the false-positive column from a corpus that "
            "has one."
        ),
        all_malicious=True,
    ),
    ExternalCorpus(
        id="picklecloak-chains",
        name="PickleCloak AEG chains",
        url="https://github.com/Lyutoon/PickleCloak/archive/909fff715f065d690c3d5475f324a931d97349fc.tar.gz",
        commit="909fff715f065d690c3d5475f324a931d97349fc",
        member_prefix="gadget/aeg/container/pickles/",
        license="none declared (all rights reserved)",
        origin="https://github.com/Lyutoon/PickleCloak",
        note=(
            "Chained-exploit variants from the same pipeline. NO BENIGN HALF: "
            "a scanner that flags every file scores 100%, so read detection "
            "here only alongside the false-positive column from a corpus that "
            "has one."
        ),
        all_malicious=True,
    ),
)


def corpus_dir(corpus: ExternalCorpus) -> Path:
    return CACHE_DIR / corpus.id


def is_fetched(corpus: ExternalCorpus) -> bool:
    d = corpus_dir(corpus)
    return d.is_dir() and any(d.iterdir())


def fetch(corpus: ExternalCorpus) -> int:
    """Download and extract one corpus. Returns the file count."""
    dest = corpus_dir(corpus)
    if is_fetched(corpus):
        return len(list(dest.iterdir()))

    dest.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(corpus.url) as response:  # noqa: S310 - pinned HTTPS
        blob = response.read()

    count = 0
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                continue
            # Archive paths start with a repo-name/commit prefix, so match on
            # the suffix rather than the whole path.
            if corpus.member_prefix not in member.name:
                continue
            # Flatten into one directory and take only the basename, which
            # also neutralises any path-traversal entry in the archive.
            name = Path(member.name).name
            if not name or name.startswith("."):
                continue
            extracted = tar.extractfile(member)
            if extracted is None:
                continue
            (dest / name).write_bytes(extracted.read())
            count += 1
    return count


def label_of(corpus: ExternalCorpus, filename: str) -> bool | None:
    """True if malicious, False if benign, None if the author does not say.

    Never guesses. A file the corpus does not label is excluded from scoring.
    """
    if filename in corpus.unlabelled:
        return None
    if corpus.all_malicious:
        return True
    if filename in corpus.asserted_malicious:
        return True
    if filename.startswith("malicious"):
        return True
    if filename.startswith("benign"):
        return False
    return None


def fetch_all() -> int:
    ok = True
    for corpus in CORPORA:
        try:
            n = fetch(corpus)
            print(f"  {corpus.id}: {n} files  [{corpus.license}]")
        except Exception as exc:
            print(f"  {corpus.id}: FAILED ({exc})")
            ok = False
    if ok:
        print()
        print("These are real exploits. They are gitignored and are never")
        print("loaded or unpickled, only scanned as bytes.")
    return 0 if ok else 1


def purge() -> None:
    """Delete the cache. Worth having, since it holds working exploits."""
    if CACHE_DIR.exists():
        shutil.rmtree(CACHE_DIR)
        print(f"removed {CACHE_DIR}")


if __name__ == "__main__":
    import sys

    if "--purge" in sys.argv:
        purge()
        raise SystemExit(0)
    raise SystemExit(fetch_all())
